kind: Certificate
apiVersion: cert-manager.io/v1alpha2
metadata:
  name: affable-www
spec:
  secretName: affable-www
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - www.affable.app
