---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kiali
spec:
  endpoints:
  - port: http-metrics
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      app: kiali
