---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-operator
  namespace: operators
spec:
  template:
    spec:
      containers:
      - name: site-operator
        env:
        - name: AFFILIATE_SITE_IMAGE
          value: eu.gcr.io/code-supply/affiliate@sha256:4ee7d4a0098adfb9708749c9c582ecf445af92d75d1a79a6413f7883b662a42f
