apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-operator
  namespace: operators
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: 3m
        sidecar.istio.io/proxyCPULimit: 500m
