apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operators
resources:
- namespace.yaml
- site-operator.yaml
patchesStrategicMerge:
- site-operator-version.yaml
- read-write-filesystem.yaml
- env-vars-from-secret.yaml
