apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- site-operator.yaml
- rbac.yaml
patchesStrategicMerge:
- site-operator-version.yaml
- read-write-filesystem.yaml
- env-vars.yaml
- istio-proxy-resources.yaml
configMapGenerator:
- name: site-operator
  namespace: operators
  files:
  - env-vars/AFFILIATE_SITE_IMAGE
