---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: site-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  verbs:
  - create
  - delete
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
- apiGroups:
  - site-operator.code.supply
  resources:
  - affiliatesites
  verbs:
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: site-operator-can-manage-things
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: site-operator
subjects:
- kind: ServiceAccount
  name: site-operator
  namespace: operators
