kind: Certificate
apiVersion: cert-manager.io/v1alpha2
metadata:
  name: www
  namespace: affable
spec:
  secretName: tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - www.affable.app
