apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: affable
resources:
- namespace.yaml
- stateful-set.yaml
replicas:
- count: 2
  name: affable
commonLabels:
  app: affable
images:
- name: affable
  newName: eu.gcr.io/code-supply/affable
  newTag: e4f04d5
