apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: affable
resources:
- namespace.yaml
- service.yaml
- headless-service.yaml
- stateful-set.yaml
- gateway.yaml
- virtual-service.yaml
- cloud-sql-egress.yaml
- google-api-egress.yaml
- sendgrid-api-egress.yaml
- rbac.yaml
replicas:
- count: 2
  name: affable
commonLabels:
  app: affable
images:
- name: affable
  newName: eu.gcr.io/code-supply/affable
  newTag: f7ebfb0
patchesStrategicMerge:
- version.yaml
