---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: affable
rules:
- apiGroups:
  - site-operator.code.supply
  resources:
  - affiliatesites
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: affable-can-manage-sites
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: affable
subjects:
- kind: ServiceAccount
  name: default
