apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: affable
spec:
  serviceName: affable
  template:
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials

      containers:

      - name: affable
        image: affable:0
        envFrom:
        - secretRef:
            name: affable

        ports:
        - name: http
          containerPort: 4000

        readinessProbe:
          httpGet:
            path: /
            port: http

      - name: cloudsql-proxy
        image: eu.gcr.io/cloudsql-docker/gce-proxy:1.17
        securityContext:
          allowPrivilegeEscalation: false

        command:
        - /cloud_sql_proxy

        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/cloudsql/key.json
        - name: INSTANCES
          value: code-supply:europe-west2:shared-belgium=tcp:5432

        volumeMounts:
        - name: google-credentials
          mountPath: /secrets/cloudsql
          readOnly: true

        resources:
          requests:
            cpu: 100m
            memory: 48Mi
          limits:
            cpu: 100m
            memory: 48Mi
