apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: affable
spec:
  hosts:
  - affable.app
  - www.affable.app
  gateways:
  - affable
  http:
  - match:
    - authority:
        exact:
          affable.app
    redirect:
      authority:
        www.affable.app
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: affable
