---
- hosts: []
  tasks:

  - name: install packages
    apt:
      name:
      - certbot
      - nginx
      - policykit-1
      update_cache: "true"
    become: "true"

  - name: remove default vhost
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    become: "true"

  - name: install code.supply vhost
    copy:
      src: ../web/code-supply/nginx.conf
      dest: /etc/nginx/sites-available/code.supply
    become: "true"

  - name: install code.supply code
    copy:
      src: ../web/code-supply/public/
      dest: /var/www/code.supply/
    become: "true"

  - name: enable code.supply vhost
    file:
      src: /etc/nginx/sites-available/code.supply
      path: /etc/nginx/sites-enabled/code.supply
      state: link
    become: "true"
