---
- hosts: all
  become: "true"

  tasks:

  - name: install apt packages
    apt:
      name:
      - python3-pip
      - python3-venv
      - nginx
      - policykit-1
      update_cache: "true"

  - name: install python packages
    pip:
      virtualenv_command: /usr/bin/python3 -m venv
      virtualenv: /certbot/env
      name:
      - certbot
      - certbot-dns-google

  - name: obtain certificate
    args:
      executable: /bin/bash
      creates: &cert-path /etc/letsencrypt/live/andrewbruce.net/fullchain.pem
    shell: |-
      tries=0
      until /certbot/env/bin/certbot certonly \
        --agree-tos \
        --non-interactive \
        --dns-google \
        --email me@andrewbruce.net \
        --domain andrewbruce.net \
        --domain '*.andrewbruce.net' \
        --domain code.supply \
        --domain '*.code.supply' \
        || [ $tries -eq 5 ]
      do
        echo "Re-trying certificate acquisition"
        (( tries++ ))
      done

  - name: link code.supply certificate
    file:
      src: *cert-path
      path: /etc/nginx/code.supply.crt
      state: link

  - name: link code.supply key
    file:
      src: /etc/letsencrypt/live/andrewbruce.net/privkey.pem
      path: /etc/nginx/code.supply.key
      state: link

  - name: remove default vhost
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: reload nginx

  - name: install code.supply vhost
    copy:
      src: ../web/code-supply/nginx.conf
      dest: /etc/nginx/sites-available/code.supply
    notify: reload nginx

  - name: install code.supply code
    copy:
      src: ../web/code-supply/public/
      dest: /var/www/code.supply/
    notify: reload nginx

  - name: enable code.supply vhost
    file:
      src: /etc/nginx/sites-available/code.supply
      path: /etc/nginx/sites-enabled/code.supply
      state: link
    notify: reload nginx

  handlers:

  - name: reload nginx
    service:
      name: nginx
      state: reloaded
