---
- hosts: all
  become: "true"

  tasks:

  - name: install apt packages
    apt:
      name:
      - nginx
      - nodejs
      - policykit-1
      - python3-pip
      - python3-venv
      update_cache: "true"

  - name: install python packages
    pip:
      virtualenv_command: /usr/bin/python3 -m venv
      virtualenv: /certbot/env
      name:
      - certbot
      - certbot-dns-google

  - name: obtain certificate
    args:
      executable: /bin/bash
      creates: &cert-path /etc/letsencrypt/live/andrewbruce.net/fullchain.pem
    shell: |-
      tries=0
      until /certbot/env/bin/certbot certonly \
        --agree-tos \
        --non-interactive \
        --dns-google \
        --email me@andrewbruce.net \
        --domain andrewbruce.net \
        --domain '*.andrewbruce.net' \
        --domain code.supply \
        --domain '*.code.supply' \
        || [ $tries -eq 5 ]
      do
        echo "Re-trying certificate acquisition"
        (( tries++ ))
      done

  - name: link code.supply certificate
    file:
      src: *cert-path
      path: /etc/nginx/code.supply.crt
      state: link

  - name: link code.supply key
    file:
      src: /etc/letsencrypt/live/andrewbruce.net/privkey.pem
      path: /etc/nginx/code.supply.key
      state: link

  - name: remove default vhost
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: reload nginx

  - name: install code.supply vhost
    copy:
      src: ../web/code-supply/nginx.conf
      dest: /etc/nginx/sites-available/code.supply
    notify: reload nginx

  - name: install code.supply code
    copy:
      src: ../web/code-supply/public/
      dest: /var/www/code.supply/
    notify: reload nginx

  - name: enable code.supply vhost
    file:
      src: /etc/nginx/sites-available/code.supply
      path: /etc/nginx/sites-enabled/code.supply
      state: link
    notify: reload nginx

  - name: create andrewbruce.net systemd dir
    file:
      path: /etc/systemd/system/andrewbruce.service.d
      state: directory
      mode: '0755'

  - name: install www.andrewbruce.net vhost
    copy:
      src: ../web/andrewbruce-net/nginx.conf
      dest: /etc/nginx/sites-available/www.andrewbruce.net
    notify: reload nginx

  - name: create andrewbruce.net bin dir
    file:
      path: /var/www/www.andrewbruce.net/bin
      state: directory
      mode: '0755'
      owner: www-data

  - name: install www.andrewbruce.net server
    copy:
      src: ../web/andrewbruce-net/bin/server
      dest: /var/www/www.andrewbruce.net/bin/server
      mode: '0555'
      owner: www-data
    notify: reload nginx

  - name: install www.andrewbruce.net public
    copy:
      src: ../web/andrewbruce-net/public
      dest: /var/www/www.andrewbruce.net/
      owner: www-data
    notify: reload nginx

  - name: install andrewbruce.net systemd service
    copy:
      src: ../web/andrewbruce-net/andrewbruce.service
      dest: /etc/systemd/system/andrewbruce.service
    notify: restart andrewbruce

  - name: enable andrewbruce.net systemd service
    systemd:
      name: andrewbruce
      enabled: "true"
      state: started

  - name: enable www.andrewbruce.net vhost
    file:
      src: /etc/nginx/sites-available/www.andrewbruce.net
      path: /etc/nginx/sites-enabled/www.andrewbruce.net
      state: link
    notify: reload nginx

  handlers:

  - name: reload nginx
    service:
      name: nginx
      state: reloaded

  - name: restart andrewbruce
    systemd:
      name: andrewbruce
      state: restarted
